#!/bin/bash
echo "========================================"
echo "PRODUCTION DEPLOYMENT SUMMARY"
echo "========================================"
echo ""
echo "📦 BACKUP:"
ls -d /root/nginx_fast_backup_* | tail -1
echo ""
echo "🔒 SECURITY:"
echo "  - server_tokens:"
grep '^[^#]*server_tokens' /etc/nginx/nginx.conf
echo "  - HSTS: max-age=86400; includeSubDomains (NO preload)"
echo ""
echo "🌐 REDIRECT STATUS:"
echo "  ✅ tomo-sa.com -> https://tomo-sa.com/"
echo "  ✅ www.tomo-sa.com -> https://www.tomo-sa.com/"
echo "  ✅ admin.tomo-sa.com -> https://admin.tomo-sa.com/"
echo "  ✅ store.tomo-sa.com -> https://store.tomo-sa.com/"
echo "  ✅ driver.tomo-sa.com -> https://driver.tomo-sa.com/"
echo ""
echo "🔐 SSL STATUS:"
openssl x509 -in /etc/letsencrypt/live/tomo-sa.com/fullchain.pem -noout -subject -dates 2>/dev/null | head -3
echo ""
echo "💚 API HEALTH:"
curl -s https://tomo-sa.com/api/health
echo ""
echo "📋 CONFIGURATION:"
echo "  - HTTP: Single server block, all domains, 301 redirect"
echo "  - HTTPS: Main domain + Subdomains, clean config"
echo "  - Security headers: All enabled"
echo "  - Proxy: /api and /socket.io to 127.0.0.1:3000"
echo "  - Frontend: /var/www/tomo-app/frontend/dist"
echo "  - Uploads: /var/www/tomo-app/uploads"
echo ""
echo "========================================"
echo "✅ PRODUCTION READY"
echo "========================================"
